/* Automatically generated by p4c-ebpf from fake_ping.p4 on Tue Apr 28 16:12:40 2020
 */
#ifndef _P4_GEN_HEADER_
#define _P4_GEN_HEADER_
#include "ebpf_kernel.h"

#define MAP_PATH "/sys/fs/bpf/tc/globals"
struct Ethernet {
    u64 dstAddr; /* bit<48> */
    u64 srcAddr; /* bit<48> */
    u16 etherType; /* bit<16> */
    u8 ebpf_valid;
};

struct IPv4 {
    u8 version; /* bit<4> */
    u8 ihl; /* bit<4> */
    u8 diffserv; /* bit<8> */
    u16 totalLen; /* bit<16> */
    u16 identification; /* bit<16> */
    u8 flags; /* bit<3> */
    u16 fragOffset; /* bit<13> */
    u8 ttl; /* bit<8> */
    u8 protocol; /* bit<8> */
    u16 hdrChecksum; /* bit<16> */
    u32 srcAddr; /* bit<32> */
    u32 dstAddr; /* bit<32> */
    u8 ebpf_valid;
};

struct ICMP {
    u8 type; /* bit<8> */
    u8 code; /* bit<8> */
    u16 checksum; /* bit<16> */
    u32 icmp_header; /* bit<32> */
    u8 ebpf_valid;
};

struct Headers_t {
    struct Ethernet ethernet; /* Ethernet */
    struct IPv4 ip; /* IPv4 */
    struct ICMP icmp; /* ICMP */
};

#if CONTROL_PLANE
static void init_tables() 
{
    u32 ebpf_zero = 0;
}
#endif
#endif
